KiCad/kicad-website

README.adoc
config.toml
content/discover/features.adoc
layouts/index.html
layouts/partials/footer.html
static/css/kicad.css

These commits contain various suggestions, tell me if anything is unwanted.
Hopefully I will find the time to fill more content.
What is the preferred form of root-relative links ? There are uses of  `/download`, `{{ .Site.BaseURL }}`, and even `http://misc.c4757p.com/fe.png`. Should we stick with the first?

Various changes

---

content/discover/getting-started.adoc
content/help/file-formats.adoc

As simple as it gets.
URL's need fixing.
No install/setup information included,
I suggest to put that in the platform download pages.

Simple getting started

---

content/discover/3dviewer.adoc
content/discover/eeschema.adoc
content/discover/pcbnew.adoc
layouts/index.html

Fix "no" typo in Eeschema features, simplify double titles of features, add links to full size images on homepage.
Suggestion for later: on the homepage, end with a carousel of projects made with KiCad, linking to the dedicated page.

Small improvements

---

content/help/getting-started.adoc

@reportingsjr and I rewrote this page to improve the structure and feel. Let me know if there's anything you don't like.

Rewrite Getting Started

---

content/discover/eeschema.adoc
layouts/index.html

Just a few suggested changes. I also noticed that some files seem to have cr/lf and others only cr for the EOL character, but I don't know what to do about that.

Suggested (minor) changes to web pages

---

content/community/irc.adoc

I rewrote the IRC page to make it a bit more informative and perhaps a bit clearer.

Rewrite IRC page

---

content/download/linuxmint.adoc

Rewrite Linux Mint download instructions similarly to my Ubuntu rewrite PR

Rewrite Linux Mint download instructions

---

content/download/linuxmint.adoc
content/download/ubuntu.adoc

I missed a couple steps in the Ubuntu and Linux Mint install instructions earlier.

Complete the install instructions for Ubuntu, Linux Mint

---

content/help/external-tools.adoc

Add link to FreeCAD PCB plugin in external tool

---

content/download/source.adoc

Typo in download/build

---

content/contribute/build-linux.adoc
content/contribute/build-osx.adoc
content/contribute/build-windows.adoc
content/discover/in-the-media.adoc
content/help/getting-started.adoc

There is a asciidoc parse error in build-osx.adoc that I'm unable to resolve.
It looks like the "++" is parsed as asciicdoc tags.
Look almost at the bottom om the rendered page.

Cosmetic changes

---

config.toml
content/post/new-website-anno-2015.adoc
layouts/_default/summary.html
layouts/partials/breadcrumb.html
layouts/post/single.html
layouts/section/download.html
layouts/section/post.html
static/css/kicad.css

Added breadcrumbs, thinner content column, improved full-article news, international format for dates...
Reduce <p> spacing and remove hyphens from breadcrumbs site-wide.

More appealing design for the blog

---

layouts/partials/header.html

See http://gohugo.io/templates/go-templates/#internet-explorer-conditional-comments-using-pipes:e2fc23c6497b774f0cb0b339042e10c3

Wrap IE conditional to prevent comment stripping

---

content/help/report-a-bug.adoc

Corrected a minor typo.

---

content/help/external-tools.adoc

mention one autorouter, and link to step-by-step instructions for installing that autorouter and autorouting a KiCad PCB.

mention autorouter

---

content/download/linux-mint.adoc
content/download/open-suse.adoc
content/download/ubuntu.adoc
content/download/windows.adoc

Hi folks!
Per the mailing list, I prepared a pull request to help clarify the RC situation on the download pages.  Feel free to change the wording--I am not 100% up to speed with the whole website like you folks probably are so I might have made some mistakes.
Thanks!

RC clarification

---

content/download/linux-mint.adoc
content/download/ubuntu.adoc

So that no prompt happens during pasting the whole block.

Add --yes flag for add-apt-repository

---

content/help/system-requirements.adoc

Added system requirements as discussed in ml.
Comments?

Added system requirements for KiCad

---

layouts/section/download.html

Had a friend complain that RC2 wasn't out because of this page.

Update RC reference and blog post url

---

content/about/kicad.adoc

Change KiCad license from GPL v2 to GPL v3

---

content/discover/eeschema.adoc
content/discover/in-the-media.adoc
content/discover/screenshots.html

Feel free to discard or to use.

Minor tweaks to the discover area

---

content/help/system-requirements.adoc

Minor tweaks to System Requirements page.

---

content/contribute/developers.adoc

Last one, @nickoe  :)
The website is beautiful and wonderful and everyone has done a really good job.  Thanks everyone!

Tweaked developer page.

---

content/download/linux-mint.adoc
content/download/ubuntu.adoc

I also updated capitalization of KiCad on the Ubuntu download page.

Updated linux mint downloads page to reflect stable release.

---

content/download/debian.adoc
content/download/fedora.adoc
content/download/linux-mint.adoc
content/download/open-suse.adoc
content/download/osx.adoc
content/download/ubuntu.adoc
content/download/windows.adoc

I also changed the wording a touch on the fedora download page.

Adding install info for 4.0.0 on fedora.

---

content/help/documentation.adoc

I've created the rows for spanish document already translated and built

add links for spanish documents in gsik and eeschema

---

content/help/documentation.adoc

add link for a new spanish manual translated
Regards

add link for spanish kicad manual

---

content/help/documentation.adoc

add link for spanish cvpcb manuals

---

content/help/documentation.adoc

add link for spanish pcbnew manual in help docs

---

content/help/documentation.adoc

add link for spanish gerbview manual

---

content/help/documentation.adoc

add spanish Pl_Editor manual link

---

content/download/ubuntu.adoc

https://launchpad.net/~js-reynaud/+archive/ubuntu/kicad-4 show Kicad 4.0.2

Update version info to 4.0.2 for Ubuntu

---

content/download/arch-linux.adoc

https://www.archlinux.org/packages/community/x86_64/kicad/ show 4.0.2 as current version

Update version to 4.0.2 for ArchLinux

---

content/download/osx.adoc

Is there anywhere else we have to change it?

Bumped OS X to 4.0.2

---

content/help/file-formats.adoc

This is a user request: https://forum.kicad.info/t/ipc-d-356a-netlist-capability/2714/6

Add .d356 extension

---

content/help/documentation.adoc

This should be merged after this other PR:
https://github.com/KiCad/kicad-doc/pull/367

Add link to Project Manager docs in Russian

---

content/post/kicad-hackathon-july-2016-at-cern.adoc

Plus a little bit of rewording. The whole article is now in past tense rather than being mixed tense.

Paragraphs plz

---

content/help/documentation.adoc

- add Pcbnew in Deutsch
- add Pl_editor in Francais

add translated docs

---

content/post/git-announcement.adoc

This the announcement for the move to Git for KiCad development.

Git announcement post

---

content/post/release-4.0.4.adoc

Stable release 4.0.4 announcement blog post.

Release 4.0.4.adoc

---

content/help/report-a-bug.adoc

The website looks great! Keep up the good work, folks!

Fixed reference to Ubuntu 16.04.

---

content/download/debian.adoc
content/download/fedora.adoc
content/download/gentoo.adoc
content/external-tools/stepup.adoc

Take them or leave them!  Keep up the great work, folks, this site looks great!

More minor tweaks.

---

content/contribute/developers.adoc

Just some minor tweaks.  Feel free to accept some and reject others.

Minor tweaks to developer page.

---

content/post/gerber-x2-support.adoc

Add Gerber X2 support announcement to blog posts.

Gerber x2 support announcement

---

content/community/sites.adoc

I added another forum in Spanish, this one is discourse based
like kicad.info, which is more confortable to me.

Add another kicad forum in Spanish.

---

content/help/known-system-related-issues.adoc

Advised in bug report #1003859

Add another method for solving Radeon card issues

---

content/download/debian.adoc

fix link to ngspice bug report in Debian build instructions

---

.travis.yml
config.toml
content/about/licenses/gplv2.adoc
content/about/licenses/gplv3.adoc
content/download/arch-linux.adoc
content/download/debian.adoc
content/download/fedora.adoc
content/download/gentoo.adoc
content/download/linux-mint.adoc
content/download/open-suse.adoc
content/download/osx.adoc
content/download/snappy.adoc
content/download/source.adoc
content/download/ubuntu.adoc
content/download/windows.adoc
content/help/file-formats.adoc
content/help/migration-from-old-stable.adoc
content/post/release-4.0.2.adoc
content/post/release-4.0.3.adoc
content/post/release-4.0.4.adoc
content/post/release-4.0.5.adoc
content/post/release-4.0.6.adoc
content/post/release-4.0.7.adoc
layouts/download/single.html
layouts/index.html
layouts/partials/header.html

Changes to work with hugo 0.30
Requires updating hugo on the server and locally to 0.30.
Nothing wrong the breadcrumbs :P Apparently we always did the menu weights wrong so that's fixed.
Per task item #220

Fixes for hugo 0.30 compatibility. 

---

content/download/arch-linux.adoc

Update version number for Arch

---

content/about/kicad.adoc
content/contribute/developers.adoc
content/download/osx.adoc
content/help/known-system-related-issues.adoc
content/help/system-requirements.adoc

I swear I made this PR before--but maybe I forgot to submit it.  Let me know if you have any feedback.

Changed OS X to MacOS.

---

content/klc/G1.1.adoc

- Comma
- Plus
- As per KLC
Matches PR for KLC - https://github.com/KiCad/kicad-library-utils/pull/167 - which is already merged

Added two more legal characters

---

content/libraries/download.adoc

- Added links to https://kicad.github.io

Improved library download page

---

content/libraries/klc.adoc
content/libraries/klc_history.adoc

- New characters allowed
Fixes https://github.com/KiCad/kicad-website/pull/227#issuecomment-342835957

Bumped KLC revision to 3.0.01

---

content/post/symbol-lib-table.adoc

This post contains the necessary information for a successful transition to the symbol library table.

Symbol library table release announcement.

---

content/post/symbol-lib-table.adoc

Pushed symbol library table code to dev branch so get this back on line.

Unrescind symbol library table blog post.

---

content/libraries/external.adoc
content/libraries/third_party.adoc

Currently links to Digi-Key libs

Added external libraries page

---

content/libraries/third_party.adoc

Link to Sparkun KiCad libraries, on GitHub

Added entry for SparkFun libs

---

content/contribute/developers.adoc

Some links on the contributors page were broken! Fixed.

Fix broken links

---

content/klc/S4.5.adoc
content/klc/S5.2.adoc
content/libraries/klc.adoc
content/libraries/klc_history.adoc

- KLC S5.2: clarified the presence or not-presence of pin-count in FPFilters
- KLC S4.5: added link to S5.2
@SchrodingersGat Could you have a look? Thanks,
JAN

KLC: extended S5.2 to explain pin-count in FPFilters

---

content/klc/S3.2.adoc
content/libraries/klc.adoc
content/libraries/klc_history.adoc

Solves issue https://github.com/KiCad/kicad-symbols/issues/214

[KLC] Clarify rule regarding fontsize for symbol fields

---

content/klc/F2.1.adoc
content/klc/S5.2.adoc
content/libraries/klc.adoc
content/libraries/klc_history.adoc

Add missing ThermalVias suffix to generic suffix lists.

[KLC] Remove mentions of the obsolete suffix 'ThermalPad(s)'

---

content/libraries/klc_history.adoc

The dates in the KLC history page where wrong.

The January KLC edits are already in 2018.

---

content/help/known-system-related-issues.adoc

See: https://bugs.launchpad.net/kicad/+bug/1755360

Add a note about OpenGL not working with Wayland

---

content/contribute/docs-team.adoc

Added reference to the GUI Translation HOWTO in the contribute section

Added reference to the GUI Translation HOWTO in the contribute section

---

content/help/documentation.adoc

Add links to Indonesian translation of GSIK and KiCad manual.

Add links to Indonesian translation

---

content/download/osx.adoc

Re-release macOS V5

---

content/download/linux-mint.adoc
content/download/osx.adoc
content/download/source.adoc
content/download/ubuntu.adoc
content/download/windows.adoc

*NOTE* I was unable to run 'hugo server' to test the changes. I did my best to verify the links, but please validate the changes yourself.

Update 5.0.1 release links

---

content/download/source.adoc
layouts/section/download.html

Also, fix a typo: never -> newer

Update source download page to 5.0.2

---

content/klc/F3.6.adoc
content/klc/F5.2.adoc
content/klc/F9.3.adoc
content/libraries/klc.adoc
content/libraries/klc_history.adoc

This fixes issues #288, #341 and #333

Clarify some KLC rules

---

content/blog/release-5.1.0.adoc

Additionally clarify file compatibility

Grammar suggestions and tightening wording

---

content/klc/F5.4.adoc
content/libraries/klc_history.adoc

Related https://github.com/KiCad/kicad-library-utils/pull/286

Add KLC rule for overlapping graphical elements

---

content/blog/project-leader-announcement.adoc

Fix typos/punctuation on Project announcement post

---

content/klc/F4.4.adoc
content/klc/F5.1.adoc
content/klc/F6.3.adoc
content/klc/F7.7.adoc
content/klc/S2.1.adoc
content/klc/S4.1.adoc
content/libraries/klc.adoc
content/libraries/klc_history.adoc

@poeschlr 
Can you please take a look at this? Some of these came from your PR at https://github.com/KiCad/kicad-website/pull/407.

Minor updates

---

content/libraries/contribute.adoc

The contribution page was quite outdated. Updated to the current way we handle things.

Clarify how to contact the library team

---

content/klc/S4.3.adoc

This PR fixes formatting and typo problems introduced in 6864251dafd8cabe.
Also please see issue #359.

Fix klc s4.3

---

content/community/sites.adoc

As requested by Dave Jones.
https://twitter.com/eevblog/status/1176031721797517317

Add EEVblog forum KiCAD section

---

content/download/sabayon.adoc

Sabayon 5.1.4 is the current release listed at the Sabayon link

Update Sabyon release version

---

config.toml

Changed from Yahoo to Group.io

Update user mailing list link to group.io

---

.travis.yml

This is to workaround
https://github.com/gjtorikian/html-proofer/issues/544

Use html-proofer 3.13.0

---

content/download/fedora.adoc
content/help/system-requirements.adoc

Please see the official announcement for more information:
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/BB4ECDFSJ66AQU63ZKNYROEFMMLSLFUK/

Fedora 29 has reached its End-Of-Life

---

content/help/system-requirements.adoc

* Make clear that this support list is for stable 5.1
* Layout guidelines for how long each distribution is supported
* Update the versions currently under support
I will also be sending an email to the developer list asking for feedback on this vesioning proposal.

Revise support policy for Linux distributions

---

content/libraries/contribute.adoc

Improve library contribution guidelines based on past experiences as a library maintainer.

Improve library contribution guidelines

---

content/blog/2020/development-highlight-altium-importer.adoc

Correct minor grammatical error in post (its vs it's)

Correct typo in development-highlight-altium-importer.adoc
