KiCad/kicad-website

content/discover/made-with-kicad.html
Mrk Industries was relaunched as Palta Tech (www.paltatech.com) this year. Also, EITI description was a bit too long so I made it more concise.
=> Update Mrk Industries name and EITI cleanup

layouts/download/single.html, layouts/partials/sidebar.html, static/css/kicad.css
Add a sidebar to navigate between the sub pages of the download section.
I am not proud of having copied the layout file but could not figure out a better way.
Additionally, I enclosed all sidebars in pills to separate them from the page contents.
=> Add a sidebar to download subpages

static/css/kicad.css
A typo in the CSS has made the two columns on the front page have unequal text justification.
=> Fix typo in CSS: content-section justification

content/download/ubuntu.adoc
Add more user-friendly download instructions for Ubuntu. Ubuntu users don't usually like to be slapped with shell commands.
=> Rewrite Ubuntu download instructions

static/display/KICAD/Download+Kicad/index.html, static/display/KICAD/KiCad+Documentation/index.html, static/display/KICAD/KiCad+EDA+Software+Suite/index.html, static/display/KICAD/Tutorials/index.html, static/display/KICAD/Windows/index.html
The URLs were found on reverse link search engines.
For the homepage and the download index, the redirects were created manually in `/static`, see:
http://discuss.gohugo.io/t/index-aliases/138
=> Add redirections for URLs of some existing backlinks

layouts/_default/archive.html, layouts/_default/list.html, layouts/_default/single.html, layouts/_default/terms.html, layouts/download/single.html, layouts/partials/sidebar.html, layouts/post/single.html, layouts/section/download.html, layouts/section/made-with-kicad.html, layouts/section/post.html, static/css/kicad.css
Not a lot changes, this is mostly polishing.
- The code for similar layouts is now more similar, this should help for further evolutions.
- Ensure the 'row' div is used for every container. This helped fix the extra padding on /download.
- Only when the main menu is collapsed will sidebars be pushed after the content.
- Give more love to pages like /discover/
Preview: http://dallens.fr/
=> More homogenous content column, keep sidebar for medium grid

content/help/file-formats.adoc
I'm surprised that this list of file formats doesn't yet mention ".adoc", the format that this list itself is in.
(See http://github.com/KiCad/kicad-website/pull/51 for previous discussion).
=> mention the ".adoc" file format

content/download/arch-linux.adoc
Updated the information for Arch Linux's download page.
=> KiCad 4.0.0 is now in Arch's community repo.

content/help/migration-from-old-stable.adoc
Tried to improve the explanation. Added the crucial info that you need a text editor for .kicad_pcb files. Changed the section titles for clarity.
Prompted by the following question:
https://forum.kicad.info/t/instaling-version-4-0-1-trouble/1983
=> Add details to the migration procedure

content/help/documentation.adoc
I sorted all entries on the Documentation website in a alphabetical order as people will find the searched item easier. And finally adding the available German manuals.
=> Sort all entries on Documentation alphabetical, adding links for available German documentation

content/help/documentation.adoc
After the latest work on various German translation of the manuals I added them into the tables on the documentation site. I also re reorder the English manuals on top of the section, if needed. This was suggested in #119 by marekr.
=> Adding new German section entries into the linking of documentation

static/css/kicad.css
Improve table of contents styling to separate it from page contents.
There might be an issue with the numerals. I don't understand how the bullets of `<li>` containing a second-level `<ul>` are hidden in the current website. I can't reproduce that locally.
Example: why do first-level bullets stop after "Utilities"? http://kicad-pcb.org/help/documentation/
=> Improve TOC styling to separate it from page contents

content/help/documentation.adoc
Add links to the current French translations of the documentation.
Condense the introductory text to have less things blocking users from getting to the actual doc.
=> Add links to FR docs, more concise introduction

content/download/debian.adoc
Finally version 4.0.2 was entering testing/sid and 4.0.1 is accepted in backports.
=> Debian: update package status and download information

content/download/debian.adoc
The actual version 4.0.2 is now also available in jessie-backports.
=> Debian: update package information on Stable-Backports

content/download/debian.adoc
The current KiCad source need also at least the libcairo-dev package to
get the source successful built.
=> debian.adoc: adding additional dep package for build from source

content/download/debian.adoc
Finally also kicad 4.0.5 in jessie-backports has arrived, all recent
Debian repositories have now the actual upstream version available.
Thanks to Simon Richter who prepared the upload to jessie-backports!
=> debian: update information for Debian packages of kicad

content/download/debian.adoc
The ftpmaster have accepted the current packaging of 4.0.6 and by this
Debian can provide the current upstream stable version in unstable and
testing now.
=> debian: 4.0.6 has reached unstable and testing

content/post/release-4.0.7.adoc
There was a duplicate reference to a change made for KiCad 4.07
=> Remove duplicate link to change

content/download/debian.adoc
Backports will need some more time.
But please wait to merge this PR until 4.0.7 is migrated into testing, this should happen in the next four days until Sunday in the morning.
https://tracker.debian.org/pkg/kicad
=> debian: 4.0.7 is now in unstable and testing

content/download/source.adoc
On the source download page, the version and links are incorrect.
=> Fix source downloads and version from 4.0.6 to 4.0.7

content/download/debian.adoc
The current upstream version 4.0.7 is now available in
jessie-backports-sloppy and stretch-backports.
=> debian: 4.0.7 is now backported for Jessie and Stretch

content/contribute/developers.adoc
As discussed: https://lists.launchpad.net/kicad-developers/msg31930.html
I have no idea how insert empty lines in a fixed-width block of text, so instead I used dots (lines 200, 203, 206, 209 in the patched file). If you know how it should be done, please fix it.
=> Changelog tags description

content/post/release-5.0.0.adoc
bullets changed from `-` to `*` so that the multi-level bullets render properly in the Github preview
=> Additions and reformatting to 5.0.0 release draft

content/contribute/developers.adoc
One should not keep an information duplicated, as it is a potential
source of incoherency.
The note about changelog tags is already added to the developers
documentation. It will be refreshed the next time the Doxygen
documentation is regenerated.
=> Replace the commit message format description with a link

content/libraries/klc.adoc, content/libraries/klc_history.adoc, data/fpnaming/cap_tant_smd.yaml
This is to avoid the impression that tantulum capacitor footprints
are manufacturer specific.
We noticed the confusion in reported issue: https://github.com/KiCad/kicad-packages3D/issues/176
The renaming happened in this merged pull request: https://github.com/KiCad/kicad-footprints/pull/136
=> [KLC update] Tantalum caps: move letter code towards the back

content/klc/F3.6.adoc, content/libraries/klc.adoc, content/libraries/klc_history.adoc
This pull request does fix some errors in the examples in the connector naming convention.
We discovered the problem in the discussion for pull request https://github.com/KiCad/kicad-footprints/pull/153
=> [KLC] Fixed the examples in rule 3.6 (connector naming)

content/klc/F6.3.adoc, content/libraries/klc.adoc, content/libraries/klc_history.adoc
Discussion in https://github.com/KiCad/kicad-footprints/issues/211.
=> KLC: specify paste coverage range for exposed pads.

content/libraries/download.adoc
As we got a few complaints from users of the stable release that the new libs to not work for them i decided to make it more clear on the download page that the new repos are intended for KiCad version 5.
I also added a requirement section on the github.io download pages, added this information to the readme files and gave the repos them selves a description that mentions kicad 5 as well. I hope this will be enough to guide users to the correct version of the library.
Edit: We will try to provide a backport release of the new library that will be compatible with kicad 4. But as this is extra work we do not want to do this too early. (We want to finish the transfer from the old library first.)
=> Make it more clear what library is intended for what kicad release

content/download/ubuntu.adoc
Some update on Ubuntu (ppa) installation instruction. 
- ppa-kicad became legacy
- nightly build can be installed in same time than stable version
- ...
English is not my main language. Could have some mistakes...
=> Update Ubuntu installation instructions

content/klc/F7.3.adoc, content/libraries/klc.adoc, content/libraries/klc_history.adoc
Industry standards now suggest the use of rounded rectangle pads. For
this reason it is now allowed to use rounded rectangles in addition to
rectangle pads for marking pin 1 in polarized through hole components.
=> Allow rounded rectangle pads for marking pin 1

content/klc/F2.1.adoc, content/klc/S3.7.adoc, content/libraries/klc.adoc, content/libraries/klc_history.adoc, layouts/shortcodes/fp_prefix.html
Parts that include an exposed pad, a mounting pad or a shield pad are
now better defined.
The rules written down in this change are already used in the library.
=> Clarify footprint naming and pin numbers for special pins

content/download/fedora.adoc
The 3D model libraries have recently been moved to a separate package kicad-packages3d for both the nightlies (see https://github.com/KiCad/fedora-packaging/pull/18) and the official builds of KiCad 5.0. The installation instructions on the website should be updated to reflect this change.
Fedora 26 has reached EOL in May 2018 and is not supported anymore. It is time to remove its repology tag.
@nickoe
You may want to also update the installation instructions on the KiCad copr page: https://copr.fedorainfracloud.org/coprs/g/kicad/kicad/
=> Update installation instructions for Fedora

content/klc/F2.2.adoc
F2.2: Improve clarity & wording
Resolves this issue: https://github.com/KiCad/kicad-website/issues/318
And this issue: https://github.com/KiCad/kicad-website/issues/319
Ignore the first commit description below. The commits afterwards  undid it. Idid NOT end up adding any such "B" to the example. I was confused. See this old pull request here for info: https://github.com/KiCad/kicad-website/pull/323.
This pull request is ready to be accepted.
=> F2.2 improvements

content/libraries/klc.adoc
1. Fix spelling: "have" to "has".
2. Move this section to the top, where it is more visible by people with
busy lives who are looking to quickly make a good contribution. This
solves this issue here:
https://github.com/KiCad/kicad-website/issues/321.
3. Add a usage example, and improve wording.
=> Move and improve "KLC Helper Scripts" section

layouts/blog/single.html
The back link in blog post goes to http://kicad-pcb.org/post/. This is an index of all blog posts without a proper layout. The list of blog posts with the correct layout is at http://kicad-pcb.org/blog/.
=> Make back link go to blog page iof folder index

content/klc/S4.7.adoc, content/libraries/klc.adoc, content/libraries/klc_history.adoc
- Active low prefixes/suffixes as discussed on https://github.com/KiCad/kicad-symbols/pull/651
- Clarification added for pin names where not the full name needs a bar above
Thanks!
=> KLC S4.7: active low clarifications

content/download/debian.adoc
5.0.0 is available at the link (At least for the most popular Architectures)
=> Update backports version on debian stretch

content/help/file-formats.adoc
STEP files are now natively supported by KiCad 5 and are commonly used in KiCad 4 projects using the KiCad Step-Up tools. Their existence should be documented on [the File Formats page](http://kicad-pcb.org/help/file-formats/).
=> Add STEP files to File Formats page

content/download/fedora.adoc
This commit adds Fedora 29 to the download section of the web site.
=> Add Fedora 29 to the download section of the web site.

content/download/fedora.adoc
Remove Fedora 27 from the download page.
=> Fedora 27 has reached end-of-life status

content/about/kicad.adoc
Originally read:
```But it has no other meaning other now being the name of the software suite. ```
=> Accidentally a word on the about page

content/download/osx.adoc, content/download/windows.adoc, content/help/known-system-related-issues.adoc, content/help/system-requirements.adoc
This commit clarifies Wayland support and gives specific guidance to which operating systems are supported and when we anticipate that the support will end.
This also clarifies what support means (bugs must reproduce on supported systems before being addressed).
=> Adding support specifics

config.toml
Google plus was shutdown earlier this year
=> Remove Google plus link

content/download/fedora.adoc, content/help/system-requirements.adoc
Update the Fedora EOL dates now that Fedora 30 has been released.  In general a Fedora release has about a one year life-span.
=> Update Fedora EOL dates

content/download/osx.adoc
The header in the download section still had 10.11 in it, and it caused some user confusion. This updates that reference to be 10.12 now.
=> Update Mac OS version to 10.12

content/help/upgrading.adoc
Once 5.1.1 is released, we can remove this entirely and simply direct
people to use the latest stable release.
=> Add blurb for translating old version files

layouts/section/download.html
Fix an incorrect link pointing to the old 5.1.2 release notice on the downloads page.
=> Update release notice link to point to 5.1.4

content/download/debian.adoc
Complete rewrite of the content about the information for downloading
KiCad packages for the Debian releases.
Repology doesn't list packages for Old-Stable Backports, this needs to
get adjusted always manually.
=> Download: Rewrite of the Debian download page

content/help/known-system-related-issues.adoc
There seems to be some confusion about the high DPI screen support in KiCad, so adding this information to the common issues page seems like a good thing.
=> Add high DPI issues to the frequent issues page

content/help/known-system-related-issues.adoc
Rephrase the advice for High DPI screens to specify that automatic scaling is an option that should be enabled by default, and describe where to modify it if it is not enabled.
=> Update High DPI advice on the known issues page

content/download/fedora.adoc, content/help/system-requirements.adoc
Fedora 31 is now released, so update the web pages to include it.
=> Add Fedora 31 to the web pages

content/download/linux-mint.adoc
Linux Mint does not have a maintainer for KiCad.  Additionally, only
some varieties of Mint work with the listed method
=> Clarify Linux Mint usage

content/klc/F5.2.adoc, content/klc/F5.3.adoc, content/libraries/klc.adoc, content/libraries/klc_history.adoc
* Fab comes from the nominal size of the component
* Silk outlines should be such that they allow for the part
tolerances, so a worst-case, but in-spec, part cannot
overlap silk that is supposed to be visible after assembly.
* Courtyards allow for part tolerances so that worst-case, but
in-spec, parts cannot violate the clearances.
----
The idea here is to ensure that a part that is within the promised tolerances (either from a standard like a JEDEC or from the datasheet) will never violate the courtyard (most critical) or cover silkscreen that should be visible (annoying for THT, bad for SMD)
The Fab rule is mostly to guide the user on the right dimensions to use when presented with a min/nominal/max dimensioning system.
This will probably mean that some existing footprints don't meet …
=> KLC F5.1,2,3: Clarify rules for parts with tolerances

content/download/_supported-note.adoc, content/download/flatpak.adoc, content/download/freebsd.adoc, content/download/gentoo.adoc, content/download/linux-mint.adoc, content/download/open-suse.adoc, content/download/sabayon.adoc
While we provide distribution links to various linux distros, it is
important that users see the limitations of our support policy when
downloading.
This also downgrades the placement of Linux Mint below the supported distributions
=> Adding an unsupported note to relevant distros

layouts/partials/donate.html
We have engaged with the Linux Foundation because they offer a much
better means of support for Open Source project development.  We should
make this clear on the website.  There are also significant tax benefits
to US donations for donating via LF.
=> Clarify preferred donation path

layouts/partials/donate.html
The abbreviations clarify what each button does.
The Linux Foundation allows the 'TLF' abbreviation specifically.  This
is listed at https://www.linuxfoundation.org/trademark-usage/ in the
first bullet under the section 
**Rules and Policies Applicable to Marks Owned by The Linux Foundation**
Here is the view on an iPhone 6/7/8 that has resolution 375x667
=> Update donate button text

content/download/fedora.adoc
@nickoe - now that you have removed the reference to mangelajo/kicad from Copr, it probably makes sense to remove it from the KiCad web page too.
This patch does that.
=> Fedora: Remove instructions regarding the mangelajo/kicad repository.

content/download/_js-reynaud-ppa.adoc
On Linux Mint, default is to NOT install recommends packages (very strange option... anyway...).
So I have added instruction for mint user to force installation of recommended packages...
=> Update ppa installation information

content/download/debian.adoc
On Debian, the sources.list directory is named "sources.list.d", not "sources.lists.d"
=> Changed folder path for apt sources.list.d

content/help/known-system-related-issues.adoc
Update some of the bug links to GitLab (for the ones that have them), and also add new text mentioning the known menu vertical size issue and how to fix it.
=> Update High DPI compatibility section

content/contribute/code-of-conduct.adoc
Add the new project code of conduct to the contributor section of the website so that it is visibile.
See https://lists.launchpad.net/kicad-developers/msg43603.html
=> Add project code of conduct

content/download/_js-reynaud-ppa.adoc
When installing either `kicad-nightly-demo` or `kicad-demo`, I get the following messages:
```~$ sudo apt install kicad-demo
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package kicad-demo is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However, the following packages replace it:
kicad-demos
```
---
```
~$ sudo apt install kicad-nightly-demo
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package kicad-nightly-demo is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source …
```
=> Modify demo installation samples

content/download/debian.adoc
Small update after the backported package for KiCad got accepted into stretch-backports-sloppy.
=> Debian Stretch: update available version in backports

content/download/fedora.adoc
Fedora 30 has gone EOL, so it should be removed from the KiCad web site.
=> Fedora 30 is now EOL

content/help/known-system-related-issues.adoc, content/help/system-requirements.adoc
depending on the version, there are some issues with GTK and wxWidgets, that need extra package installations.
=> add instructions for Linux MATE desktop
